services:
  web:
    build: .
    container_name: dracinlovers_app
    restart: always
    # Menggunakan network mode host agar bisa akses MySQL localhost server secara langsung
    # Tanpa perlu setup gateway IP yang rumit
    network_mode: "host"
    volumes:
      - ./instance:/app/instance
      - ./migrations:/app/migrations
      - ./app/static:/app/app/static # Mount static files agar bisa diakses Nginx Host
      # Uncomment baris di bawah ini saat development agar perubahan kode langsung terlihat
      # - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production

  bot:
    build: .
    container_name: dracinlovers_bot
    restart: always
    network_mode: "host"
    command: python bot.py
    env_file:
      - .env
    depends_on:
      - web
